title: "André's Homepage"
description: "A personal blog about my work and projects."



plugins:
  - jekyll-remote-theme

lsi: false
safe: false
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

show_downloads: true
google_analytics: G-9ZPC22X0V6